"""Helpers for formatting review findings as GitHub markdown comments."""

from app.models import Finding, InlineComment

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
}

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def format_inline_body(finding: Finding) -> str:
    emoji = SEVERITY_EMOJI[finding.severity]
    category = finding.category.upper()
    return (
        f"{emoji} **[{category}] {finding.title}**\n\n"
        f"{finding.description}\n\n"
        f"**Suggestion:**\n"
        f"```\n{finding.suggestion}\n```\n"
    )


def format_summary_comment(ranked_findings: list[Finding], repo: str, pr_number: int) -> str:
    from collections import Counter

    counts = Counter(f.severity for f in ranked_findings)
    file_count = len({f.file for f in ranked_findings})

    lines = [
        "## 🤖 AI Code Review Summary\n",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {counts.get('critical', 0)} |",
        f"| 🟠 High     | {counts.get('high', 0)} |",
        f"| 🟡 Medium   | {counts.get('medium', 0)} |",
        f"| 🔵 Low      | {counts.get('low', 0)} |",
        "",
        f"> **{len(ranked_findings)} total findings** across **{file_count} file(s)**.",
        "",
    ]

    if ranked_findings:
        lines += [
            "### Top findings",
            "",
        ]
        for f in ranked_findings[:5]:
            emoji = SEVERITY_EMOJI[f.severity]
            lines.append(f"- {emoji} **{f.title}** — `{f.file}:{f.line}`")

    lines += [
        "",
        "---",
        "*Review generated by [AI Code Reviewer](https://github.com) · "
        "Please verify suggestions before acting on them.*",
    ]
    return "\n".join(lines)


def rank_findings(findings: list[Finding]) -> list[Finding]:
    """Sort by severity then confidence (descending)."""
    return sorted(
        findings,
        key=lambda f: (SEVERITY_ORDER[f.severity], -f.confidence),
    )


def deduplicate_findings(findings: list[Finding]) -> list[Finding]:
    """Remove duplicate findings on the same file+line+category."""
    seen: set[tuple] = set()
    unique = []
    for f in findings:
        key = (f.file, f.line, f.category)
        if key not in seen:
            seen.add(key)
            unique.append(f)
    return unique
